/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Doctor;

import Controlador.ControladorAtenderCita;
import Controlador.ControladorCancelarCita;
import Controlador.ControladorRegistrarMulta;
import Modelo.Cita;
import Modelo.Doctor;
import Modelo.Multa;
import Vista.Paciente.VerHistorial;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AtenderCita extends javax.swing.JFrame {

    private ControladorAtenderCita controladorCita;
    private ControladorRegistrarMulta controladorMulta;
    private Doctor doctor;
    private Cita cita;
    /**
     * Creates new form AtenderCita
     */
    public AtenderCita( Doctor doctor) {
        initComponents();
        setLocationRelativeTo(null);
        this.controladorCita = new ControladorAtenderCita();
        this.controladorMulta = new ControladorRegistrarMulta();
        this.doctor = doctor;
        llenarAgenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTratamientos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConclusiones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnMultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxAgenda = new javax.swing.JComboBox();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ATENDER CITA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtTratamientos.setColumns(20);
        txtTratamientos.setRows(5);
        jScrollPane1.setViewportView(txtTratamientos);

        jLabel2.setText("Escribe aquí los tratamientos para el paciente:");

        txtConclusiones.setColumns(20);
        txtConclusiones.setRows(5);
        jScrollPane2.setViewportView(txtConclusiones);

        jLabel3.setText("Escribe aquí las conclusiones de la cita");

        btnConfirmar.setText("CONFIRMAR ATENCION");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnHistorial.setText("Ver historial del paciente");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnMultar.setText("Multar paciente");
        btnMultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha:");

        cbxAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Paciente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnHistorial)
                        .addGap(18, 18, 18)
                        .addComponent(btnMultar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbxAgenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnConfirmar)
                        .addGap(101, 101, 101))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbxAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnHistorial)
                    .addComponent(btnMultar))
                .addGap(37, 37, 37))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para resetear los campos
     */
    private void resetearCampos(){
        txtConclusiones.setText("");
        txtTratamientos.setText("");
        llenarAgenda();
    }
    
    /**
     * Metodo para llenar el combobox de la agenda del doctor
     */
    private void llenarAgenda(){
        cbxAgenda.removeAllItems();
        if( doctor.getAgenda().isEmpty() ){
            cbxAgenda.addItem("Ya no hay citas en su agenda");
            lblPaciente.setText("");
            btnHistorial.setEnabled(false);
            btnMultar.setEnabled(false);
            btnConfirmar.setEnabled(false);
            return;
        }
        cbxAgenda.addItem("Seleccione una cita de su agenda");
        
        for (Cita citaAgendada : doctor.getAgenda()) {
            cbxAgenda.addItem(citaAgendada);
        }
    }
    
    /**
     * Metodo que maneja el evento del boton volver para retroceder de ventana
     * @param evt 
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VistaDoctor vistaDoctor = new VistaDoctor(this.doctor);
        vistaDoctor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Metodo que maneja el evento del boton de confirmar la atencion de la cita para ejecutar su accion
     * @param evt 
     */
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //Validando los campos
        if( cbxAgenda.getSelectedIndex()==0 ){
            JOptionPane.showMessageDialog(null, "Cita no válida");
            return;
        }
        
        if( txtConclusiones.getText().isBlank() ){
            JOptionPane.showMessageDialog(null, "Faltan las conclusiones");
            return;
        }
        
        if( txtTratamientos.getText().isBlank()  ){
            JOptionPane.showMessageDialog(null, "Faltan los tratamientos");
            return;
        }
        
        
        //Obtenemos los datos para anexarlos al historial del paciente
        String conclusiones = txtConclusiones.getText();
        String tratamientos = txtTratamientos.getText();
        Cita citaSeleccionada = (Cita) cbxAgenda.getSelectedItem();
        
        controladorCita.confirmarAtencion(cita,conclusiones,tratamientos);
        
        boolean eliminada = controladorCita.getControlador().eliminarCita(citaSeleccionada.getPaciente().getDocumento());
        if( eliminada ){
            JOptionPane.showMessageDialog(null, "Cita atendida con exito");
            resetearCampos();                  
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrió algún error");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * Metodo para ver el historial del paciente
     * @param evt 
     */
    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        VerHistorial historial = new VerHistorial(cita.getPaciente(),this);
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * Metodo que maneja el evento del boton multar paciente para multarlo si no asistió
     * @param evt 
     */
    private void btnMultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultarActionPerformed
        //Confirmamos si se desea multar al paciente
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea multar al paciente " + cita.getPaciente().getNombre() + "?");
        
        if( confirmacion==0 ){
            //Creamos la multa y la registramos
            Multa multa = new Multa(cita);
            controladorMulta.descuentoMulta(multa);
            boolean añadida = controladorMulta.añadirMulta(multa);
            boolean cancelada = controladorCita.getControlador().eliminarCita(cita.getPaciente().getDocumento());
            if( añadida && cancelada){
                JOptionPane.showMessageDialog(null, "Se ha multado al paciente: " + cita.getPaciente().getNombre());
                resetearCampos();
            }
        }
    }//GEN-LAST:event_btnMultarActionPerformed

    /**
     * Metodo para que cada vez que se seleccione una cita se muestren sus detalles
     * @param evt 
     */
    private void cbxAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgendaActionPerformed
        //Si el primer item está seleccionado no es una cita válida
        if( cbxAgenda.getSelectedIndex()==0 ){
            lblFecha.setText("No hay una cita seleccionada");
            lblPaciente.setText("No hay una cita seleccionada");   
            return;
        }
        
        Cita citaSeleccionada = (Cita) cbxAgenda.getSelectedItem();
        
        if( citaSeleccionada != null ){
            lblFecha.setText( citaSeleccionada.getFecha().toString() );
            lblPaciente.setText( citaSeleccionada.getPaciente().toString() );

            this.cita = citaSeleccionada;
        }
    }//GEN-LAST:event_cbxAgendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnMultar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cbxAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JTextArea txtConclusiones;
    private javax.swing.JTextArea txtTratamientos;
    // End of variables declaration//GEN-END:variables
}
